# Site wide configuration

title:            Abbass Marouni
locale:           en_US
url:              https://blog.marouni.fr
remote_theme:     "mmistakes/minimal-mistakes"

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Layout
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true


# Site owner
owner:
  name: Abbass Marouni
  avatar: bio-photo-3.jpg
  bio: "What can I know?\nWhat should I do?\nWhat should I aspire to?"
  email: abbass.marouni@gmail.com
  disqus-shortname: marouni
  twitter: abbassmarouni
  google:
    plus: #username
    analytics: 'UA-50476639-1'
    tracking_id : 'UA-50476639-1'
    verify: 
    ad-client: 
    ad-slot: 
  github: marouni
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: Abbass Marouni

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
